### ISSUE TITLE
cannot compile on ubuntu

### ISSUE THREAD

**Issue by robust-lu** [marlam/pmdsim#2]
i compile the project on ubuntu16.04. and got messages below in 96%.

CMakeFiles/pmdsim.dir/src/osgwidget.cpp.o: In function `osgDB::readNodeFile(std::string const&)':
osgwidget.cpp:(.text._ZN5osgDB12readNodeFileERKSs[_ZN5osgDB12readNodeFileERKSs]+0x2c): undefined reference to `osgDB::readNodeFile(std::string const&, osgDB::Options const*)'
CMakeFiles/pmdsim.dir/src/osgwidget.cpp.o: In function `osgDB::writeNodeFile(osg::Node const&, std::string const&)':
osgwidget.cpp:(.text._ZN5osgDB13writeNodeFileERKN3osg4NodeERKSs[_ZN5osgDB13writeNodeFileERKN3osg4NodeERKSs]+0x34): undefined reference to `osgDB::writeNodeFile(osg::Node const&, std::string const&, osgDB::Options const*)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libosgViewer.so: undefined reference to `osgText::TextBase::setFont(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/lib64/libosgText.so.100: undefined reference to `osgDB::readRefObjectFile(std::string const&, osgDB::Options const*)'
/usr/local/lib64/libosgText.so.100: undefined reference to `osgDB::findDataFile(std::string const&, osgDB::CaseSensitivity)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libosgViewer.so: undefined reference to `osgText::TextBase::setText(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/lib64/libosgText.so.100: undefined reference to `osgDB::readObjectFile(std::string const&, osgDB::Options const*)'
/usr/local/lib64/libosgText.so.100: undefined reference to `osg::StateSet::setRenderBinDetails(int, std::string const&, osg::StateSet::RenderBinMode)'
/usr/local/lib64/libosgText.so.100: undefined reference to `osgDB::Registry::getReaderWriterForExtension(std::string const&)'
/usr/local/lib64/libosgText.so.100: undefined reference to `osg::ApplicationUsage::addUsageExplanation(osg::ApplicationUsage::Type, std::string const&, std::string const&)'
/usr/local/lib64/libosgText.so.100: undefined reference to `osgDB::convertStringPathIntoFilePathList(std::string const&, std::deque<std::string, std::allocator<std::string> >&)'
/usr/local/lib64/libosgText.so.100: undefined reference to `osgDB::findFileInPath(std::string const&, std::deque<std::string, std::allocator<std::string> > const&, osgDB::CaseSensitivity)'
/usr/local/lib64/libosgText.so.100: undefined reference to `osgDB::getSimpleFileName(std::string const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/pmdsim.dir/build.make:614: recipe for target 'pmdsim' failed
make[2]: *** [pmdsim] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pmdsim.dir/all' failed
make[1]: *** [CMakeFiles/pmdsim.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

my OSG version is 3.2.3. is this the problem of version? how can i solve it?

**Comment by marlam** [comment]
Hi, I see that you use a custom version of OSG and not the packages from Ubuntu 16.04. Apparently both are mixed in the build (e.g. `/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libosgViewer.so` versus `/usr/local/lib64/libosgText.so.100`). This is likely the problem.

Please try to either uninstall all Ubuntu OSG packages (`apt-get purge *openscenegraph*`), or remove your own OSG in /usr/local and use only the Ubuntu package `libopenscenegraph-dev`.

Does that solve the problem?

**Comment by robust-lu** [comment]
yes,i remove the ubuntu package and it is ok, but here is another problem. 

/usr/bin/ld: warning: libicui18n.so.58, needed by //home/robust-lu/anaconda2/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.58, needed by //home/robust-lu/anaconda2/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.58, needed by //home/robust-lu/anaconda2/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `u_errorName_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_setMillis_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_getAlias_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_inDaylightTime_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `u_strToLower_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_getStandardName_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `u_strToUpper_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_setSubstChars_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_getMaxCharSize_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_getTimeZoneDisplayName_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_fromUnicode_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_open_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_getDefaultName_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_getDefaultTimeZone_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_clone_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_getDSTSavings_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucol_strcoll_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_close_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_countAvailable_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_openCountryTimeZones_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucol_open_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_compareNames_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_close_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_getAvailableName_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_openTimeZoneIDEnumeration_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_open_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucol_setAttribute_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_openTimeZones_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `uenum_close_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_countAliases_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucol_close_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucol_getSortKey_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucal_get_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `uenum_next_58'
//home/robust-lu/anaconda2/lib/libQt5Core.so.5: undefined reference to `ucnv_toUnicode_58'

i have installed the icu package in anaconda2, libicui18n.so.58 libicuuc.so.58 libicudata.so.58 is in anaconda2/lib dir. how to solve?

**Comment by marlam** [comment]
First, pmdsim should use Qt4, not Qt5 (the OSG/Qt plugin still uses Qt4, too). Second, it is probably easier to again just use the Ubuntu package `libqt4-dev` instead of your own Qt5 installation in `/home/robust-lu/anaconda2`.

**Comment by robust-lu** [comment]
ok, it works. when i run ./pmdsim, it appears "QGLFormat::setSamples: Cannot have negative number of samples per pixel -1" in terminal and PMDSim window appears, any influence?

**Comment by marlam** [comment]
No, that message can be ignored.
